# Generated by Django 5.2.6 on 2026-02-05 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('host_name', models.CharField(default='Host', max_length=50)),
                ('drawn_numbers', models.TextField(blank=True, default='')),
                ('current_number', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('game_started', models.BooleanField(default=False)),
                ('players_who_selected_this_round', models.TextField(blank=True, default='')),
                ('current_turn_player', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('channel_name', models.CharField(blank=True, max_length=255)),
                ('board_state', models.TextField(default='')),
                ('is_host', models.BooleanField(default=False)),
                ('is_connected', models.BooleanField(default=True)),
                ('is_ready', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.room')),
            ],
            options={
                'unique_together': {('room', 'name')},
            },
        ),
    ]
